{
 "title": "Pod network",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Node count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count(ping_durations_seconds_count) by (source_zone, source_node_name)) by (source_zone)",
     "legendFormat": "{{ source_zone }}"
    }
   ]
  },
  {
   "title": "Bandwith per connection (avg over downloads)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(16*1024*1024)/(sum(abs(delta(download_durations_seconds_sum{}[1m]))< 50) by (source_zone,dest_zone)/sum(abs(delta(download_durations_seconds_count{}[1m]))) by (source_zone,dest_zone))",
     "legendFormat": "{{ source_zone }} => {{ dest_zone }}"
    }
   ]
  },
  {
   "title": "Latencies quantile 0.99 by zones",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(ping_durations_seconds{quantile='0.99'} > 0) by (source_zone, dest_zone)",
     "legendFormat": "{{dest_zone}} => {{ source_zone }}"
    }
   ]
  }
 ]
}