resources:
  - namespace.yaml
  - service.yaml
  - grafanadashboard.yaml
  - networkpolicy.yaml
  - role.yaml
  - clusterrole.yaml
  - serviceaccount.yaml
  - rolebinding.yaml
  - clusterrolebinding.yaml
  - daemonset.yaml
  - servicemonitor.yaml
  - pod.yaml
