apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-latency
  namespace: kube-latency
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-latency
subjects:
- kind: ServiceAccount
  name: kube-latency
  namespace: kube-latency
