---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-latency
  namespace: kube-latency
  labels:
    app.kubernetes.io/name: kube-latency
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-latency
  namespaceSelector:
    matchNames:
    - kube-latency
  endpoints:
  - port: http